# Model checkpoint
model: available_models/product-pred/smiles/atom/x1-reag+/pre-trained/model_step_500000.pt

# Test data to use
src: ./data/product-pred/smiles/atom/x1-reag+/src-test.txt
tgt: ./data/product-pred/smiles/atom/x1-reag+/tgt-test.txt

# Batch options 
batch_size: 4096
batch_type: tokens

# Where results are saved
output: ./results/product-pred/smiles/atom/x1-reag+/pre-trained/test_predictions.txt

# Which GPU to use
gpu: 0