# Base path for anything saved (vocab, transform, embeddings, ...)
save_data: ./data/product-pred/smiles/atom/x1-reag+/pre-trained/save_data.train.src

# Save vocabulary
src_vocab: ./data/product-pred/smiles/atom/x1-reag+/src_vocab.vocab
share_vocab: True

# Prevent overwriting of existing files (or not)
overwrite: True

# Log file
log_file: ./logs/product-pred/smiles/atom/x1-reag+/pre-trained/logs.log

# Corpus opts
data:
  corpus_1:
    path_src: ./data/product-pred/smiles/atom/x1-reag+/src-train.txt
    path_tgt: ./data/product-pred/smiles/atom/x1-reag+/tgt-train.txt
  valid:
    path_src: ./data/product-pred/smiles/atom/x1-reag+/src-val.txt
    path_tgt: ./data/product-pred/smiles/atom/x1-reag+/tgt-val.txt

# Add pre-trained embeddings
both_embeddings: ./data/product-pred/smiles/atom/x1-reag+/w2v_embeddings.txt
embeddings_type: word2vec
word_vec_size: 200

# Place to save the checkpoints
save_model: ./available_models/product-pred/smiles/atom/x1-reag+/pre-trained/model.model
save_checkpoint_steps: 10000
keep_checkpoint: 20
seed: 1234

# Training steps
train_steps: 500000
valid_steps: 10000
warmup_steps: 8000
report_every: 100

# Transformer architecture
decoder_type: transformer
encoder_type: transformer
word_vec_size: 256
rnn_size: 256
layers: 4
transformer_ff: 2048
heads: 8
global_attention: general
global_attention_function: softmax
self_attn_type: scaled-dot

# Solver options
accum_count: 4
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 2.0
max_grad_norm: 0.0

# Batch options 
batch_size: 4096
batch_type: tokens
normalization: tokens
dropout: 0.1
label_smoothing: 0.0
max_generator_batches: 32
param_init: 0.0
param_init_glorot: True
position_encoding: True
share_embeddings: False

# Train on 4 GPU
world_size: 1 
gpu_ranks:
- 0
- 1
- 2
- 3
